version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7

  pre-build:
    - cd frontend/
    - npm install
  build:
    commands:
      - npm run test:nowatch
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: frontend/build/
