version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - cd frontend/
      - npm install
  build:
    commands:
      - npm build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: frontend/public/