version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - cd frontend/
      - npm run test:nowatch
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: frontend/build/

  secondary-artifacts:
    transformedCF:
      base-directory: backend/
      files:
        - transformed.yaml