version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
      nodejs: 12

  pre_build:
    commands:
      - aws --version
      - cd backend/
      - pip install chalice
      - pip install -r requirements.txt
      - cd ..
      - cd frontend/
      - npm install
      - cd ..
  build:
    commands:
      - cd backend/
      - chalice package /tmp/packaged
      - aws cloudformation package --template-file
          /tmp/packaged/sam.json --s3-bucket $LAMBDA_S3_BUCKET
          --output-template-file transformed.yaml
      - cd ../frontend
      - npm run test:nowatch
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: frontend/build/

  secondary-artifacts:
    transformedCF:
      base-directory: backend/
      files:
        - transformed.yaml