export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const ADDED_CARD = "ADDED_CARD";
export const DELETED_CARD = "DELETED_CARD"
export const FAILED_ADD_CARD = "FAILED_ADD_CARD";
export const FAILED_DELETE_CARD = "FAILED_DELETE_CARD";
export const VIEWED_CARDS = "VIEWED_CARDS";
export const FAILED_VIEW_CARDS = "FAILED_VIEW_CARDS";
export const TOPPED_UP_CARD = "TOPPED_UP_CARD";
export const FAILED_TOP_UP = "FAILED_TOP_UP";

export const LOGOUT = "LOGOUT";

export const ACCOUNT_DELETED = "ACCOUNT_DELETED";

export const USER_ERROR = "USER_ERROR";

export const EMAIL_UPDATED = "EMAIL_UPDATED";

export const PASSWORD_UPDATED = "PASSWORD_UPDATED";

export const PASSWORD_ERROR = "PASSWORD_ERROR";
